apiVersion: apps/v1
kind: Deployment
metadata:
  name: wooolxapp
  labels:
    app: wooolxapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wooolxapp
  template:
    metadata:
      labels:
        app: wooolxapp
    spec:
      containers:
        - env:
          - name: APIKEY
            value: APIKEYVAL
          name: wooolapp 
          image: dfranciswoolies/ciarecruitment-bestapiever:247904
          ports:
          - containerPort: 80
      nodeSelector:
        nodeName: aks-woolx-30884846-vmss000000

---
apiVersion: v1
kind: Service
metadata:
  name: wooolxsvc
  labels:
    app: wooolxapp
spec:
  type: NodePort
  ports:
  - port: 80
    name: "http"
    targetPort: 80
    nodePort: 30080
  selector:
    app: wooolxapp